client_config_backend: settings
client_config:
  client_id: 839729133085-nn5lofi06ka9ke1ij4r1g3es7ov2ugfl.apps.googleusercontent.com
  client_secret: 13ZZmXFJb7VScU3U7qONET_f

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.appdata